blog/urls.py
from blog.models import Article
from django.conf.urls import url, include
from django.views.generic import TemplateView
from blog.views import (start_page,
                        # article_list,
                        article_list_ajax,
                        articles_list_update,
                        article_create,
                        article_update,
                        article_delete,
                        # article_detail,
                        send_mail_ajax,
                        article_detail_ajax,
                        add_like,
                        photo)


app_name = 'blog'


urlpatterns = [
    # url(r'^mine/$', MyView.as_view(), name='my-view'),

    # include urls_api
    url(r'^api/', include('blog.class_based.urls')),

    url(r'^$', start_page, name='start_page'),
    url(r'^send-mail-ajax$', send_mail_ajax, name='send_mail_ajax'),

    # url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/list/$', article_list, name='article_list'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/list-ajax/$', article_list_ajax, name='article_list'),

    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/list/update/$', articles_list_update,
        name='articles_list_update'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/create/$', article_create, name='article_create'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/(?P<article_slug>.*)/edit/$', article_update,
        name='article_update'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/(?P<article_slug>.*)/delete/$', article_delete,
        name='article_delete'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/(?P<article_slug>.*)/$', article_detail_ajax,
        name='article_detail_ajax'),
    # url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/(?P<article_slug>.*)/$', article_detail,
    #     name='article_detail'),
    url(r'^(?P<item_slug>.*)/list/$', photo, name='photo'),
    url(r'^add_like/(?P<id>[0-9]+)/$', add_like, name='add_like')
    #url(r'^3d-max/proposals/$', proposals, name='proposals'),
]

    # url(r'^contact/$', TemplateView.as_view(template_name='contact_page.html')),

comment/urls.py
from django.conf.urls import url
from comment.views import comment_create

app_name = 'comment'


urlpatterns = [
    # url(r'^create/$', comment_create, name='comment_create'),
    url(r'^create/(?P<id>[0-9]+)/$', comment_create, name='create'),
    ]


comment/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from blog.models import Article
from loginsys.models import Profile


class Comments(models.Model):
    # Translators: This message appears on the home page only

    comments_create = models.DateTimeField(auto_now_add=True, verbose_name=_("Дата створення"))
    comments_text = models.TextField(verbose_name=_('Текст коментаря'), max_length=200)
    comments_article = models.ForeignKey(Article, related_name="comments", verbose_name=_('Коментар для статті'),
                                         on_delete=models.CASCADE)
    comments_user = models.ForeignKey(Profile, related_name="comments", verbose_name=_("Автор коментаря"))

    class Meta:
        db_table = 'comments'
        verbose_name = _("Коментар")
        verbose_name_plural = _("Коментарі")
        # order_with_respect_to = 'comments_article'

    def __str__(self):
        return self.comments_text

comment/forms.py
from comment.models import Comments
from django import forms
from django.utils.translation import ugettext_lazy as _


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['comments_text']
        widgets = {'comments_text': forms.Textarea(attrs={'class': 'form-control', 'rows': 4})}
        labels = {'comments_text': _('Введіть текст коментаря')}
        error_messages = {'comments_text': {'max_length': _('Даний коментар дуже довгий.')}, }

    def clean_comments_text(self):
        comments_text = self.cleaned_data['comments_text']
        num_words = len(comments_text.split())
        if num_words < 4:
            raise forms.ValidationError(_('Дуже мало слів!'))
        return comments_text


comment/views.py
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.http import JsonResponse, HttpResponse
from comment.forms import CommentForm
from blog.models import Article
from loginsys.models import Profile
from django.core.paginator import Paginator
from django.contrib import messages
from django.utils.translation import gettext as _
import time


def comment_create(request, id=None):
    data = dict()
    article = Article.objects.get(id=id)
    form = CommentForm()
    now = time.time()

    if request.session.get('pause', False) and request.session.get('start_time', False) > now:
        messages.error(request, _('Ви вже залишили коментар, зачекайте хвилину.'), extra_tags='error')

    else:
        if request.is_ajax() and request.method == 'POST':
            form = CommentForm(request.POST)

            if form.is_valid() and request.user.is_authenticated():
                comment = form.save(commit=False)
                comment.comments_article = article
                comment.comments_user = Profile.objects.get(pk=request.user.pk)                            # АБО comment.comments_from = auth.get_user(request)  АБО comment.comments_from_id = auth.get_user(request).id
                comment.save()

                form = CommentForm()

                messages.success(request, _('Коментар добавлений успішно!'), extra_tags='success')

                request.session['pause'] = True
                request.session['start_time'] = time.time() + 20

                comments = article.comments.all().order_by('-comments_create')
                current_page = Paginator(comments, 4)
                page_number = request.GET.get('page', 1)
                data['html_comments'] = render_to_string('partial_comments_list.html',
                                                         {"comments": current_page.page(page_number)},
                                                         request=request)

                data['form_is_valid'] = True

            else:
                data['form_is_valid'] = False

    message = messages.get_messages(request)
    if message:
        data['html_messages'] = render_to_string('messages.html',
                                                 {'messages': message},
                                                 request=request)

    context = {'form': form,
               'article': article}
    data['html_form'] = render_to_string('partial_comment_form.html',
                                         context,
                                         request=request)
    return JsonResponse(data)

comment/templates/comment/partial_comment_form.html


<form id="form-massage" class="form-row" action="{% url 'comment:create' article.id %}" method="POST">
    <fieldset>
        <div class="form-group">
            {% csrf_token %}
            {{ form }}
            <button id="btn-submit" type="submit" class="btn btn-primary">добавити коментар</button>
        </div>
    </fieldset>
</form>


comment/templates/comment/partial_comment_pagination.html


<div id="pagination" class="col-lg-10  col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
    <ul class="pager">
        {% if comments.has_previous %}
            <li class="previous"><a href="?page={{ comments.previous_page_number }}">← Новіші коментарі</a></li>
        {% else %}
            <li class="previous disabled"><a href="">← Новіші коментарі</a></li>
        {% endif %}
        {% if comments.has_next %}
            <li class="next"><a href="?page={{ comments.next_page_number }}">Старіші коментарі →</a></li>
        {% else %}
            <li class="next disabled"><a href="">Старіші коментарі →</a></li>
        {% endif %}
        <style>
            .article.well {
                margin-bottom: 10px;
            }
        </style>
    </ul>
</div>

comment/templates/comment/partial_comments_list.html

<div class="col-md-offset-1">
    <h4><strong>Коментарі:</strong></h4>
</div>
<hr>
<div>
    {% for comment in comments %}

        <p>{{comment.comments_text}}</p>
        <img class="img-responsive ava" src="{{ comment.comments_user.avatar.url }}"
             alt="{{comment.comments_user.username}}">
        <p><strong>{{comment.comments_user.user.username}}</strong> <em>{{comment.comments_create}}</em></p>
        <hr>

    {% endfor %}
</div>
